title: My Site Title
description: >- # your site description
  A blog about programming, science, and other chaos.
baseurl: "" # leave empty unless your site is in a subpath
url: "https://your-username.github.io" # replace with your GitHub Pages URL

# Use Serial Programmer theme
remote_theme: huangyz0918/serial-programmer

plugins:
  - jekyll-remote-theme
  - jekyll-paginate
